version: '3.9'

services:
    rabbitmq:
        image: rabbitmq:4.0-management
        container_name: rabbitmq
        ports:
        - "5672:5672"
        - "15672:15672"
    
    redis: 
        image: redis/redis-stack-server:latest
        ports:
        - "6379:6379"
